#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Text-Template
Version  : 1.53
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/M/MS/MSCHOUT/Text-Template-1.53.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MS/MSCHOUT/Text-Template-1.53.tar.gz
Summary  : 'Expand template text with embedded Perl'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Text-Template-license
Requires: perl-Text-Template-man
Requires: perl(Test::More::UTF8)
Requires: perl(Test::Warnings)
BuildRequires : perl(Test::More::UTF8)
BuildRequires : perl(Test::Warnings)

%description
Text::Template v1.46
This is a library for generating form letters, building HTML pages, or
filling in templates generally.  A `template' is a piece of text that
has little Perl programs embedded in it here and there.  When you
`fill in' a template, you evaluate the little programs and replace
them with their values.

%package license
Summary: license components for the perl-Text-Template package.
Group: Default

%description license
license components for the perl-Text-Template package.


%package man
Summary: man components for the perl-Text-Template package.
Group: Default

%description man
man components for the perl-Text-Template package.


%prep
%setup -q -n Text-Template-1.53

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Text-Template
cp LICENSE %{buildroot}/usr/share/doc/perl-Text-Template/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Text/Template.pm
/usr/lib/perl5/site_perl/5.26.1/Text/Template/Preprocess.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Text-Template/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Text::Template.3
/usr/share/man/man3/Text::Template::Preprocess.3
